import { useState, useEffect, useRef, useCallback } from 'react';

/**
 * IRDiffViewer — AI-powered "Before vs After Optimization" panel.
 *
 * Keeps the header as "LLVM IR Diff" but renders a human-readable explanation
 * generated by the Groq LLM instead of the raw Monaco DiffEditor.
 */

const RISK_CONFIG = {
  low:      { label: 'Low',      color: '#22c55e', bg: 'rgba(34,197,94,0.12)',  border: 'rgba(34,197,94,0.25)' },
  medium:   { label: 'Medium',   color: '#f59e0b', bg: 'rgba(245,158,11,0.12)', border: 'rgba(245,158,11,0.25)' },
  high:     { label: 'High',     color: '#f97316', bg: 'rgba(249,115,22,0.12)', border: 'rgba(249,115,22,0.25)' },
  critical: { label: 'Critical', color: '#ef4444', bg: 'rgba(239,68,68,0.12)',  border: 'rgba(239,68,68,0.25)' },
};

function hashKey(a, b) {
  // Simple hash to use as a cache key
  let h = 0;
  const s = (a || '') + '|||' + (b || '');
  for (let i = 0; i < s.length; i++) {
    h = ((h << 5) - h + s.charCodeAt(i)) | 0;
  }
  return String(h);
}

export default function IRDiffViewer({ o0IR, o2IR, finding, sourceCode }) {
  const [explanation, setExplanation] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const cacheRef = useRef({});

  const fetchExplanation = useCallback(async (o0, o2, findingData, source) => {
    const key = hashKey(o0, o2);

    // Return cached result
    if (cacheRef.current[key]) {
      setExplanation(cacheRef.current[key]);
      setError('');
      return;
    }

    setLoading(true);
    setError('');
    setExplanation(null);

    try {
      const findingContext = findingData ? {
        readable_name: findingData.readable_name || findingData.function || '',
        category: findingData.category || '',
        severity: findingData.severity || '',
        detail: findingData.detail || '',
        fix: findingData.fix || '',
      } : {};

      const res = await fetch('/api/ir-diff-explain', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          o0_ir: o0 || '',
          o2_ir: o2 || '',
          source_snippet: source || null,
          finding_context: findingContext,
        }),
      });

      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        throw new Error(err.detail || 'Failed to generate IR explanation');
      }

      const data = await res.json();
      const result = data.explanation || {};
      cacheRef.current[key] = result;
      setExplanation(result);
    } catch (e) {
      setError(e.message || 'Failed to generate IR explanation');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (o0IR || o2IR) {
      fetchExplanation(o0IR, o2IR, finding, sourceCode);
    } else {
      setExplanation(null);
      setError('');
    }
  }, [o0IR, o2IR, finding, sourceCode, fetchExplanation]);

  // Empty state
  if (!o0IR && !o2IR) {
    return (
      <div className="glass-card p-6">
        <h3 className="text-sm font-semibold text-gray-400 uppercase tracking-wider mb-3">
          LLVM IR Diff
        </h3>
        <p className="text-gray-500 text-sm">Select a finding to view the LLVM IR difference.</p>
      </div>
    );
  }

  const risk = RISK_CONFIG[explanation?.risk_level] || RISK_CONFIG.medium;

  return (
    <div className="glass-card overflow-hidden ir-diff-panel">
      {/* Header */}
      <div className="px-5 py-3.5 border-b border-white/5 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <h3 className="text-sm font-semibold text-gray-300 uppercase tracking-wider">
            LLVM IR Diff
          </h3>
          {!loading && explanation && (
            <span
              className="ir-diff-risk-badge"
              style={{
                color: risk.color,
                background: risk.bg,
                borderColor: risk.border,
              }}
            >
              {risk.label} Risk
            </span>
          )}
        </div>
        <div className="flex items-center gap-2 text-[11px] text-gray-500">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-purple-400 opacity-70">
            <path d="M12 2a7 7 0 0 1 7 7c0 2.38-1.19 4.47-3 5.74V17a2 2 0 0 1-2 2h-4a2 2 0 0 1-2-2v-2.26C6.19 13.47 5 11.38 5 9a7 7 0 0 1 7-7z"/>
            <path d="M10 21h4"/>
          </svg>
          <span className="text-gray-500">AI-Powered Analysis</span>
        </div>
      </div>

      {/* Content */}
      <div className="p-5">
        {/* Loading state */}
        {loading && (
          <div className="ir-diff-loading">
            <div className="ir-diff-loading-icon">
              <div className="spinner" />
            </div>
            <div>
              <p className="text-sm font-medium text-gray-300">Analyzing IR changes...</p>
              <p className="text-xs text-gray-500 mt-1">
                The AI is comparing unoptimized and optimized LLVM IR
              </p>
            </div>
          </div>
        )}

        {/* Error state */}
        {!loading && error && (
          <div className="ir-diff-error">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#ef4444" strokeWidth="2">
              <circle cx="12" cy="12" r="10"/>
              <line x1="15" y1="9" x2="9" y2="15"/>
              <line x1="9" y1="9" x2="15" y2="15"/>
            </svg>
            <div>
              <p className="text-sm font-medium text-red-400">Unable to generate explanation</p>
              <p className="text-xs text-gray-500 mt-0.5">{error}</p>
            </div>
          </div>
        )}

        {/* Explanation content */}
        {!loading && !error && explanation && (
          <div className="ir-diff-content">
            {/* Before / After cards */}
            <div className="ir-diff-cards-grid">
              {/* Before (O0) */}
              <div className="ir-diff-card ir-diff-card-before">
                <div className="ir-diff-card-header">
                  <div className="ir-diff-card-dot" style={{ background: '#3b82f6' }} />
                  <span className="ir-diff-card-label">Before Optimization (O0)</span>
                </div>
                <p className="ir-diff-card-text">
                  {explanation.before_summary || 'No summary available.'}
                </p>
                {explanation.before_code && (
                  <pre className="ir-diff-code-block ir-diff-code-before">{explanation.before_code}</pre>
                )}
              </div>

              {/* Arrow indicator */}
              <div className="ir-diff-arrow">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <line x1="5" y1="12" x2="19" y2="12"/>
                  <polyline points="12 5 19 12 12 19"/>
                </svg>
              </div>

              {/* After (O2) */}
              <div className="ir-diff-card ir-diff-card-after">
                <div className="ir-diff-card-header">
                  <div className="ir-diff-card-dot" style={{ background: '#f59e0b' }} />
                  <span className="ir-diff-card-label">After Optimization (O2)</span>
                </div>
                <p className="ir-diff-card-text">
                  {explanation.after_summary || 'No summary available.'}
                </p>
                {explanation.after_code && (
                  <pre className="ir-diff-code-block ir-diff-code-after">{explanation.after_code}</pre>
                )}
              </div>
            </div>

            {/* Key Changes */}
            {explanation.key_changes && explanation.key_changes.length > 0 && (
              <div className="ir-diff-section">
                <h4 className="ir-diff-section-title">
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-cyan-400">
                    <polyline points="9 11 12 14 22 4"/>
                    <path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/>
                  </svg>
                  Key Changes
                </h4>
                <ul className="ir-diff-changes-list">
                  {explanation.key_changes.map((change, i) => (
                    <li key={i} className="ir-diff-change-item">
                      <span className="ir-diff-change-bullet">→</span>
                      <span>{change}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Why It Matters */}
            {explanation.why_it_matters && (
              <div className="ir-diff-section ir-diff-why-matters">
                <h4 className="ir-diff-section-title">
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-amber-400">
                    <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/>
                    <line x1="12" y1="9" x2="12" y2="13"/>
                    <line x1="12" y1="17" x2="12.01" y2="17"/>
                  </svg>
                  Why It Matters
                </h4>
                <p className="ir-diff-why-text">{explanation.why_it_matters}</p>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
